[[session]]
name = "relayr"
path = "~/projects/relayr"
windows = [
  "code",
  "shell",
  "api",
  "ingest",
  "cli",
  "consumer",
  "test",
  "notes",
  "git",
  "db",
]

[[window]]
name = "code"
startup_script = "nvim"

[[window]]
name = "ingest"

[[window]]
name = "api"

[[window]]
name = "db"

[[window]]
name = "cli"

[[window]]
name = "consumer"

[[window]]
name = "test"

[[window]]
name = "shell"

[[window]]
name = "notes"
path = "~/projects/chat"
startup_script = "nvim new.md"

[[window]]
name = "git"
startup_script = "lazygit"
